# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/test.runs/synth_1/croc_xilinx.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/test.cache/wt [current_project]
set_property parent.project_path /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb/include
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/include
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/include
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/include
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/register_interface/include
} [current_fileset]
set_property verilog_define {TARGET_FPGA TARGET_RTL TARGET_SYNTHESIS TARGET_VIVADO TARGET_XILINX} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/cf_math_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/addr_decode.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/addr_decode_dync.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb/apb_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/apb_uart.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/obi_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/block_swap/block_swap_config.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/croc_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/tspi/tspi_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/block_swap/block_swap_ctrl.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/bootrom/bootrom.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/cdc_2phase_clearable.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/cdc_4phase.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/cdc_reset_ctrlr_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/cdc_reset_ctrlr.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dm_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/core_wrap.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/counter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/soc_ctrl/soc_ctrl_reg_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/croc_domain.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/croc_soc.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_alu.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_compressed_decoder.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_controller.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_core.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_counter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_cs_registers.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_csr.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_decoder.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_ex_block.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_fetch_fifo.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_id_stage.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_if_stage.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_load_store_unit.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_multdiv_fast.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_multdiv_slow.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_pmp.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_prefetch_buffer.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_register_file_ff.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/cve2/cve2_wb.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/debug_rom/debug_rom.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/delta_counter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dm_csrs.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dm_mem.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dm_obi_top.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dm_sba.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dm_top.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dmi_cdc.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dmi_jtag.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/riscv-dbg/dmi_jtag_tap.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/fifo_v3.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/gpio/gpio_reg_pkg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/gpio/gpio.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/gpio/gpio_reg_top.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/lzc.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/obi_cut.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/obi_demux.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/obi_err_sbr.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/obi_intf.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/obi_mux.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/obi_sram_shim.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/obi/obi_xbar.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/register_interface/periph_to_reg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/register_interface/lowrisc_opentitan/prim_subreg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/register_interface/lowrisc_opentitan/prim_subreg_arb.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/register_interface/reg_intf.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/register_interface/reg_to_apb.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/reg_uart_wrap.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/block_swap/req_blocker.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/block_swap/req_blocker_ctrl.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/rr_arb_tree.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/rstgen.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/rstgen_bypass.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/slib_clock_div.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/slib_counter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/slib_edge_detect.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/slib_fifo.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/slib_input_filter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/slib_input_sync.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/slib_mv_filter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/soc_ctrl/soc_ctrl_reg_top.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/spill_register.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/spill_register_flushable.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/common_cells/sync.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/tech_cells_generic/fpga/tc_clk_xilinx.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/tech_cells_generic/tc_sram_impl.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/tech_cells_generic/fpga/tc_sram_xilinx.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/timer_unit/timer_unit.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/timer_unit/timer_unit_counter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/timer_unit/timer_unit_counter_presc.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/tspi/tspi_baudgeneration.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/tspi/tspi_cmd_ctrl.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/tspi/tspi_counter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/tspi/tspi_host.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/tspi/tspi_port_ctrl.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/tspi/tspi_resp_checker.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/tspi/tspi_shift_reg.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/uart_baudgen.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/uart_interrupt.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/uart_receiver.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/apb_uart/uart_transmitter.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/user_domain/user_rom.sv
  /usr/scratch/badile38/sem25f15/tspi_croc/rtl/croc_xilinx.sv
}
read_ip -quiet /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/test.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/test.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/test.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/constraints/zybo-z7.xdc
set_property used_in_implementation false [get_files /usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/constraints/zybo-z7.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top croc_xilinx -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef croc_xilinx.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file croc_xilinx_utilization_synth.rpt -pb croc_xilinx_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
