set_property SRC_FILE_INFO {cfile:/usr/scratch/badile38/sem25f15/tspi_croc/zybo/vivado/constraints/zybo-z7.xdc rfile:../../../constraints/zybo-z7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K17  IOSTANDARD LVCMOS33 }     [get_ports { sys_clk }];          #IO_L12P_T1_MRCC_35         Sch=sysclk
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G15  IOSTANDARD LVCMOS33 }     [get_ports { fetch_en_i }];    #IO_L19N_T3_VREF_35         Sch=sw[0]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P15  IOSTANDARD LVCMOS33 }     [get_ports { gpio_i[0]  }];    #IO_L24P_T3_34              Sch=sw[1]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W13  IOSTANDARD LVCMOS33 }     [get_ports { gpio_i[1]  }];    #IO_L4N_T0_34               Sch=sw[2]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T16  IOSTANDARD LVCMOS33 }     [get_ports { gpio_i[2]  }];    #IO_L9P_T1_DQS_34           Sch=sw[3]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K18  IOSTANDARD LVCMOS33 }     [get_ports { sys_reset }];       #IO_L12N_T1_MRCC_35         Sch=btn[0]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14  IOSTANDARD LVCMOS33 }     [get_ports { status_o  }];       #IO_L23P_T3_35              Sch=led[0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M15  IOSTANDARD LVCMOS33 }     [get_ports { gpio_o[0] }];       #IO_L23N_T3_35              Sch=led[1]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G14  IOSTANDARD LVCMOS33 }     [get_ports { gpio_o[1] }];       #IO_0_35                    Sch=led[2]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D18  IOSTANDARD LVCMOS33 }     [get_ports { gpio_o[2] }];       #IO_L3N_T0_DQS_AD1N_35      Sch=led[3]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V8   IOSTANDARD LVCMOS33 }     [get_ports { jtag_tms_i   }];          #IO_L15P_T2_DQS_13          Sch=jb_p[1]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W8   IOSTANDARD LVCMOS33 }     [get_ports { jtag_tdi_i   }];          #IO_L15N_T2_DQS_13          Sch=jb_n[1]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U7   IOSTANDARD LVCMOS33 }     [get_ports { jtag_tdo_o   }];          #IO_L11P_T1_SRCC_13         Sch=jb_p[2]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V7   IOSTANDARD LVCMOS33 }     [get_ports { jtag_tck_i   }];          #IO_L11N_T1_SRCC_13         Sch=jb_n[2]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V15  IOSTANDARD LVCMOS33 }     [get_ports { uart_rx_i }];          #IO_L10P_T1_34              Sch=jc_p[1]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W15  IOSTANDARD LVCMOS33 }     [get_ports { uart_tx_o }];          #IO_L10N_T1_34              Sch=jc_n[1]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T14  IOSTANDARD LVCMOS33 }     [get_ports { tspi_cs_no }];          #IO_L5P_T0_34               Sch=jd_p[1]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T15  IOSTANDARD LVCMOS33 }     [get_ports { tspi_mosi_o }];          #IO_L5N_T0_34               Sch=jd_n[1]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P14  IOSTANDARD LVCMOS33 }     [get_ports { tspi_miso_i }];          #IO_L6P_T0_34               Sch=jd_p[2]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R14  IOSTANDARD LVCMOS33 }     [get_ports { tspi_clk_o }];          #IO_L6N_T0_VREF_34          Sch=jd_n[2]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -hold -from [get_ports {fetch_en_i}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_jtag 1.000
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -hold -from [get_ports uart_rx_i]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -hold -to [get_ports uart_tx_o]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -hold -through [get_pins -of_objects [get_cells -hier -filter {ORIG_REF_NAME=="sync" || REF_NAME=="sync"}] -filter {NAME=~*serial_i}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -hold -through [get_pins -of_objects [get_cells -hier -filter {ORIG_REF_NAME =~ cdc_*src* || REF_NAME =~ cdc_*src*}] -filter {NAME =~ *async*}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -hold -through [get_pins -of_objects [get_cells -hier -filter {ORIG_REF_NAME =~ cdc_*dst* || REF_NAME =~ cdc_*dst*}] -filter {NAME =~ *async*}]
